In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_ranking as tfr

In [2]:
import pprint

In [3]:
def printds(ds, n=5):
    for example in ds.take(n):
        pprint.pprint(example)

In [4]:
# Load MSLR-WEB10K dataset from TFDS.
ds = tfds.load("mslr_web", split="train")

2022-07-06 14:19:36.414745: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".


Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/6000 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/mslr_web/10k_fold1/1.0.0.incompleteYZ57VZ/mslr_web-train.tfrecord*...:   0%|  …

Generating vali examples...:   0%|          | 0/2000 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/mslr_web/10k_fold1/1.0.0.incompleteYZ57VZ/mslr_web-vali.tfrecord*...:   0%|   …

Generating test examples...:   0%|          | 0/2000 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/mslr_web/10k_fold1/1.0.0.incompleteYZ57VZ/mslr_web-test.tfrecord*...:   0%|   …

Dataset mslr_web downloaded and prepared to ~/tensorflow_datasets/mslr_web/10k_fold1/1.0.0. Subsequent calls will reuse this data.


2022-07-06 14:24:12.333982: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
tfds.as_dataframe(ds.take(4))

bm25_anchor  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 9.997904, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                           bm25_body  \
0  [29.42768, 9.288441, 18.526854, 0.0, 18.957465...   
1  [36.243178, 24.041161, 35.895516, 40.150412, 4...   
2  [0.0, 31.099175, 30.484913, 31.105763, 0.0, 22...   
3  [12.288321, 13.075652, 12.605294, 15.993784, 1...   

                                          bm25_title  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 11.846837, 0.0, 0.0,...   
1  [9.428295, 7.181888, 27.228748, 24.879653, 24....   
2  [0.0, 28.65454, 28.65454, 16.023471, 0.0, 13.4...   
3  [7.69312, 9.684237, 11.621084, 4.758204, 10.59...   

                                            bm25_url  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 7.998056, 0.0, 0.0, ...   
1  [7.812148, 0.0, 23.955459, 0.0, 0.0, 0.0, 0.0,...   
2  [0.0, 22.842047, 22.842047, 19.6778, 0.0, 0.0,...   
3  [8.196643, 8.196643, 0.0, 8.695295, 8.196643, ...   

                                 bm25_whole_document  \
0  [28.927591, 9.288662, 18.490218, 0.0, 18.95132...   
1  [36.497524, 24.591495, 36.488682, 40.325685, 4...   
2  [0.0, 33.156394, 32.988977, 32.236219, 0.0, 22...   
3  [14.136543, 13.76887, 13.591888, 16.030504, 16...   

                                boolean_model_anchor  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                  boolean_model_body  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                 boolean_model_title  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                   boolean_model_url  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                        boolean_model_whole_document  ...  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...  ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  ...   
2  [0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, ...  ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  ...   

                           variance_of_tf_idf_anchor  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 9.003951, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                             variance_of_tf_idf_body  \
0  [27.840805, 19.929322, 36.308397, 0.0, 27.5398...   
1  [339.055495, 31.415201, 3305.919844, 1285.5990...   
2  [0.0, 1.228711, 2.72403, 2.764601, 0.0, 292.25...   
3  [23.545009, 288.426363, 147.156307, 8058.27939...   

                            variance_of_tf_idf_title  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 44.544215, 0.0, 0.0,...   
1  [7.687248, 7.687248, 14.848784, 14.848784, 14....   
2  [0.0, 0.064654, 0.064654, 0.016164, 0.0, 19.50...   
3  [18.508313, 18.508313, 74.03325, 18.508313, 18...   

                              variance_of_tf_idf_url  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 44.035199, 0.0, 0.0,...   
1  [9.020905, 0.0, 17.631846, 0.0, 0.0, 0.0, 0.0,...   
2  [0.0, 0.043984, 0.043984, 0.043984, 0.0, 0.0, ...   
3  [22.635226, 22.635226, 0.0, 22.635226, 22.6352...   

                   variance_of_tf_idf_whole_document  \
0  [27.841789, 19.918075, 

In [6]:
# Add a mask tensor.
ds = ds.map(lambda feature_map: {
    "_mask": tf.ones_like(feature_map["label"], dtype=tf.bool),
    **feature_map
})

In [7]:
printds(ds, 1)

{'_mask': <tf.Tensor: shape=(23,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])>,
 'bm25_anchor': <tf.Tensor: shape=(23,), dtype=float64, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])>,
 'bm25_body': <tf.Tensor: shape=(23,), dtype=float64, numpy=
array([29.42768 ,  9.288441, 18.526854,  0.      , 18.957465, 54.641172,
       21.541699, 34.312116, 46.042242, 34.166234, 52.930111, 54.62328 ,
       52.930111, 42.184598, 49.871447, 58.410574, 12.343549,  0.      ,
       40.597044, 40.785787, 40.785787,  0.      , 57.121089])>,
 'bm25_title': <tf.Tensor: shape=(23,), dtype=float64, numpy=
array([ 0.      ,  0.      ,  0.      ,  0.      ,  0.      , 11.846837,
        0.      ,  0.      ,  8.176028, 12.658756, 11.846837,  0.      ,
       11.846837,  0.      ,  0.    

In [8]:
# Shuffle data and create padded batches for queries with different lengths.
# Padded items will have False on `_mask`.
ds = ds.shuffle(buffer_size=1000).padded_batch(batch_size=32)

In [9]:
printds(ds, 1)

{'_mask': <tf.Tensor: shape=(32, 211), dtype=bool, numpy=
array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False]])>,
 'bm25_anchor': <tf.Tensor: shape=(32, 211), dtype=float64, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])>,
 'bm25_body': <tf.Tensor: shape=(32, 211), dtype=float64, numpy=
array([[ 3.829696, 25.809587, 21.336658, ...,  0.      ,  0.      ,
         0.      ],
       [ 0.865721, 25.001735,  0.551513, ...,  0.      ,  0.      ,
         0.      ],
       [25.162082, 23.555637, 24.891926,

In [10]:
# Create (features, labels) tuples from data and set -1 label for masked items.
ds = ds.map(lambda feature_map: (
    feature_map, tf.where(feature_map["_mask"], feature_map.pop("label"), -1.)))

In [11]:
printds(ds, 1)

({'_mask': <tf.Tensor: shape=(32, 809), dtype=bool, numpy=
array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False]])>,
  'bm25_anchor': <tf.Tensor: shape=(32, 809), dtype=float64, numpy=
array([[ 0.      ,  0.      , 29.138345, ...,  0.      ,  0.      ,
         0.      ],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ],
       ...,
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
  

In [12]:
# Create a model with Keras Functional API.
inputs = {
    name: tf.keras.Input(shape=(None, 1), dtype=tf.float32, name=name)
    for name in ds.element_spec[0]
    if name != "_mask"
}

In [13]:
inputs

{'bm25_anchor': <KerasTensor: shape=(None, None, 1) dtype=float32 (created by layer 'bm25_anchor')>,
 'bm25_body': <KerasTensor: shape=(None, None, 1) dtype=float32 (created by layer 'bm25_body')>,
 'bm25_title': <KerasTensor: shape=(None, None, 1) dtype=float32 (created by layer 'bm25_title')>,
 'bm25_url': <KerasTensor: shape=(None, None, 1) dtype=float32 (created by layer 'bm25_url')>,
 'bm25_whole_document': <KerasTensor: shape=(None, None, 1) dtype=float32 (created by layer 'bm25_whole_document')>,
 'boolean_model_anchor': <KerasTensor: shape=(None, None, 1) dtype=float32 (created by layer 'boolean_model_anchor')>,
 'boolean_model_body': <KerasTensor: shape=(None, None, 1) dtype=float32 (created by layer 'boolean_model_body')>,
 'boolean_model_title': <KerasTensor: shape=(None, None, 1) dtype=float32 (created by layer 'boolean_model_title')>,
 'boolean_model_url': <KerasTensor: shape=(None, None, 1) dtype=float32 (created by layer 'boolean_model_url')>,
 'boolean_model_whole_docum

In [14]:
inputs.keys()

dict_keys(['bm25_anchor', 'bm25_body', 'bm25_title', 'bm25_url', 'bm25_whole_document', 'boolean_model_anchor', 'boolean_model_body', 'boolean_model_title', 'boolean_model_url', 'boolean_model_whole_document', 'covered_query_term_number_anchor', 'covered_query_term_number_body', 'covered_query_term_number_title', 'covered_query_term_number_url', 'covered_query_term_number_whole_document', 'covered_query_term_ratio_anchor', 'covered_query_term_ratio_body', 'covered_query_term_ratio_title', 'covered_query_term_ratio_url', 'covered_query_term_ratio_whole_document', 'idf_anchor', 'idf_body', 'idf_title', 'idf_url', 'idf_whole_document', 'inlink_number', 'length_of_url', 'lmir_abs_anchor', 'lmir_abs_body', 'lmir_abs_title', 'lmir_abs_url', 'lmir_abs_whole_document', 'lmir_dir_anchor', 'lmir_dir_body', 'lmir_dir_title', 'lmir_dir_url', 'lmir_dir_whole_document', 'lmir_jm_anchor', 'lmir_jm_body', 'lmir_jm_title', 'lmir_jm_url', 'lmir_jm_whole_document', 'max_of_stream_length_normalized_term_f

In [15]:
norm_inputs = [tf.keras.layers.BatchNormalization()(x) for x in inputs.values()]
x = tf.concat(norm_inputs, axis=-1)

for layer_width in [128, 64, 32]:
    x = tf.keras.layers.Dense(units=layer_width)(x)
    x = tf.keras.layers.Activation(activation=tf.nn.relu)(x)
    
scores = tf.squeeze(tf.keras.layers.Dense(units=1)(x), axis=-1)

In [16]:
# Create, compile and train the model.
model = tf.keras.Model(inputs=inputs, outputs=scores)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
    loss=tfr.keras.losses.SoftmaxLoss(),
    metrics=tfr.keras.metrics.get("ndcg", topn=5, name="NDCG@5"))
model.fit(ds, epochs=3)

Epoch 1/3


/Users/lhuang/opt/miniconda3/envs/tensorflow2.8/lib/python3.8/site-packages/keras/engine/functional.py:559: UserWarning: Input dict contained keys ['_mask'] which did not match any model input. They will be ignored by the model.
  inputs = self._flatten_to_reference_inputs(inputs)


188/188 [==============================] - 17s 33ms/step - loss: 397.7796 - NDCG@5: 0.3383
Epoch 2/3
188/188 [==============================] - 8s 38ms/step - loss: 396.1713 - NDCG@5: 0.3830
Epoch 3/3
188/188 [==============================] - 8s 36ms/step - loss: 395.8642 - NDCG@5: 0.3952
