In [1]:
import tensorflow as tf
from tensorflow_serving.apis import input_pb2

import numpy as np

In [2]:
n_user = 20 # n个用户
user_age = np.arange(1,n_user+1)
user_gender = np.random.randint(0,3,n_user)
user_pay = np.random.random(n_user)

user = np.c_[user_age,user_gender,user_pay]

In [3]:
user

array([[1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [2.00000000e+00, 0.00000000e+00, 2.49130898e-01],
       [3.00000000e+00, 2.00000000e+00, 6.59294497e-01],
       [4.00000000e+00, 0.00000000e+00, 5.97369385e-01],
       [5.00000000e+00, 0.00000000e+00, 9.46561154e-01],
       [6.00000000e+00, 0.00000000e+00, 3.84917257e-01],
       [7.00000000e+00, 1.00000000e+00, 4.33658332e-01],
       [8.00000000e+00, 2.00000000e+00, 6.22913921e-01],
       [9.00000000e+00, 2.00000000e+00, 9.44642889e-02],
       [1.00000000e+01, 0.00000000e+00, 2.80989413e-01],
       [1.10000000e+01, 2.00000000e+00, 8.93398161e-01],
       [1.20000000e+01, 2.00000000e+00, 8.81666800e-02],
       [1.30000000e+01, 0.00000000e+00, 4.08566379e-01],
       [1.40000000e+01, 0.00000000e+00, 5.16955947e-01],
       [1.50000000e+01, 0.00000000e+00, 2.28009054e-01],
       [1.60000000e+01, 2.00000000e+00, 5.56269865e-01],
       [1.70000000e+01, 1.00000000e+00, 7.24997532e-02],
       [1.80000000e+01, 0.00000

In [4]:
#package info
package_type_set = np.array([1,3,5])
package_price_set = np.array([5,20,50,99])
package_type = np.repeat(package_type_set,len(package_price_set))
package_price = np.tile(package_price_set, len(package_type_set))

package_type_c = np.tile(package_type,n_user)
package_price_c = np.tile(package_price,n_user)

package_cnt = len(package_type_set)*len(package_price_set)
user_c = np.repeat(user, package_cnt, axis=0)

In [5]:
user_c

array([[1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01],
       [2.00000000e+00, 0.00000000e+00, 2.49130898e-01],
       [2.00000000e+00, 0.00000000e+00, 2.49130898e-01],
       [2.00000000e+00, 0.00000000e+00, 2.49130898e-01],
       [2.00000000e+00, 0.00000000e+00, 2.49130898e-01],
       [2.00000000e+00, 0.00000000e+00, 2.49130898e-01],
       [2.00000000e+00, 0.00000

In [6]:
#combine
context = np.c_[user_c, package_type_c,package_price_c]
context = np.repeat(context, 3, axis=0)

In [7]:
context

array([[ 1.        ,  2.        ,  0.2523836 ,  1.        ,  5.        ],
       [ 1.        ,  2.        ,  0.2523836 ,  1.        ,  5.        ],
       [ 1.        ,  2.        ,  0.2523836 ,  1.        ,  5.        ],
       ...,
       [20.        ,  0.        ,  0.48285935,  5.        , 99.        ],
       [20.        ,  0.        ,  0.48285935,  5.        , 99.        ],
       [20.        ,  0.        ,  0.48285935,  5.        , 99.        ]])

In [8]:
#item feature
item_type = np.random.randint(0,10,context.shape[0])
item_cnt = np.random.randint(0,500, context.shape[0])

In [9]:
#label
label =  np.random.randint(0,2,context.shape[0])

In [10]:
all_data = np.c_[context,item_type, item_cnt,label]
print(all_data.shape)

(720, 8)


In [11]:
all_data

array([[1.00000000e+00, 2.00000000e+00, 2.52383598e-01, ...,
        5.00000000e+00, 1.80000000e+02, 1.00000000e+00],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01, ...,
        7.00000000e+00, 3.88000000e+02, 1.00000000e+00],
       [1.00000000e+00, 2.00000000e+00, 2.52383598e-01, ...,
        1.00000000e+00, 1.65000000e+02, 0.00000000e+00],
       ...,
       [2.00000000e+01, 0.00000000e+00, 4.82859350e-01, ...,
        1.00000000e+00, 4.46000000e+02, 1.00000000e+00],
       [2.00000000e+01, 0.00000000e+00, 4.82859350e-01, ...,
        7.00000000e+00, 1.61000000e+02, 1.00000000e+00],
       [2.00000000e+01, 0.00000000e+00, 4.82859350e-01, ...,
        2.00000000e+00, 7.40000000e+01, 1.00000000e+00]])

In [12]:
feature_list = []
for i in range(all_data.shape[1]):
    if i != 2:
        arr = all_data[:,i].astype(np.int32)
        feature_list.append(arr)
    else:
        arr = all_data[:,i].astype(np.float32)
        feature_list.append(arr)

In [13]:
feature_list

[array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,
         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,
         7, 

In [14]:
def gen_ELWCsample(user_age, user_gender,user_pay, package_type, package_price,item_type, item_cnt ,label):

    # context feature: user_age, user_gender,user_pay, package_type, package_price,
    # item feature: item_type, item_cnt ,label
    context_dict = {}
    context_dict['user_age'] = _int64_feature(user_age)
    context_dict['user_gender'] =_int64_feature(user_gender)
    context_dict['user_pay'] = _float_feature(user_pay)
    context_dict['package_type'] = _int64_feature(package_type)
    context_dict['package_price'] = _int64_feature(package_price)
    context_proto = tf.train.Example(features=tf.train.Features(feature=context_dict))

    ELWC = input_pb2.ExampleListWithContext()
    ELWC.context.CopyFrom(context_proto)

    example_features = ELWC.examples.add()
    example_dict = {}
    example_dict['item_type'] = _int64_feature(item_type)
    example_dict['item_cnt'] = _int64_feature(item_cnt)
    example_dict['relevance'] = _int64_feature(label)
    exampe_proto = tf.train.Example(features=tf.train.Features(feature=example_dict))
    example_features.CopyFrom(exampe_proto)
    return ELWC

In [18]:
def _bytes_feature(value):
    """Returns a bytes_list from a string / byte."""
    if isinstance(value, type(tf.constant(0))):
        value = value.numpy()  # BytesList won't unpack a string from an EagerTensor.
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


def _float_feature(value):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))


def _int64_feature(value):
    """Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

In [19]:
raw_data = feature_list

In [20]:
raw_data[0]

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7

In [24]:
# for i in range(len(raw_data[0])):
for i in range(1):
    user_age, user_gender, user_pay, package_type, package_price, item_type, item_cnt, label = raw_data[0][i],\
                                                                                               raw_data[1][i],\
                                                                                               raw_data[2][i],\
                                                                                               raw_data[3][i],\
                                                                                               raw_data[4][i],\
                                                                                               raw_data[5][i],\
                                                                                               raw_data[6][i],\
                                                                                               raw_data[7][i]
    print(f"{user_age}")
    elwc_sample = gen_ELWCsample(user_age, user_gender, user_pay, package_type, package_price, item_type, item_cnt, label )
    print(f"{elwc_sample}")

1
examples {
  features {
    feature {
      key: "item_cnt"
      value {
        int64_list {
          value: 180
        }
      }
    }
    feature {
      key: "item_type"
      value {
        int64_list {
          value: 5
        }
      }
    }
    feature {
      key: "relevance"
      value {
        int64_list {
          value: 1
        }
      }
    }
  }
}
context {
  features {
    feature {
      key: "package_price"
      value {
        int64_list {
          value: 5
        }
      }
    }
    feature {
      key: "package_type"
      value {
        int64_list {
          value: 1
        }
      }
    }
    feature {
      key: "user_age"
      value {
        int64_list {
          value: 1
        }
      }
    }
    feature {
      key: "user_gender"
      value {
        int64_list {
          value: 2
        }
      }
    }
    feature {
      key: "user_pay"
      value {
        float_list {
          value: 0.25238358974456787
        }
      }
    }

In [25]:
with tf.io.TFRecordWriter('train_example.tfrecords') as writer:
    for i in range(len(raw_data[0])):
        user_age, user_gender, user_pay, package_type, package_price, item_type, item_cnt, label = raw_data[0][i],\
                                                                                                   raw_data[1][i],\
                                                                                                   raw_data[2][i],\
                                                                                                   raw_data[3][i],\
                                                                                                   raw_data[4][i],\
                                                                                                   raw_data[5][i],\
                                                                                                   raw_data[6][i],\
                                                                                                   raw_data[7][i]
        elwc_sample = gen_ELWCsample(user_age, user_gender, user_pay, package_type, package_price, item_type, item_cnt, label )
        if i == 0:
            elwc_sample_0 = elwc_sample
        writer.write(elwc_sample.SerializeToString())
print(elwc_sample_0)

examples {
  features {
    feature {
      key: "item_cnt"
      value {
        int64_list {
          value: 180
        }
      }
    }
    feature {
      key: "item_type"
      value {
        int64_list {
          value: 5
        }
      }
    }
    feature {
      key: "relevance"
      value {
        int64_list {
          value: 1
        }
      }
    }
  }
}
context {
  features {
    feature {
      key: "package_price"
      value {
        int64_list {
          value: 5
        }
      }
    }
    feature {
      key: "package_type"
      value {
        int64_list {
          value: 1
        }
      }
    }
    feature {
      key: "user_age"
      value {
        int64_list {
          value: 1
        }
      }
    }
    feature {
      key: "user_gender"
      value {
        int64_list {
          value: 2
        }
      }
    }
    feature {
      key: "user_pay"
      value {
        float_list {
          value: 0.25238358974456787
        }
      }
    }
 

In [27]:
import tensorflow as tf
import tensorflow_ranking as tfr
import sys

_SIZE = 'example_list_size'  # Name of feature of example list sizes.
_LABEL_FEATURE = 'relevance'
_PADDING_LABEL = -1

In [28]:
def create_context_feature_columns():
    context_feature_columns = {}
    #all context feature embedding

    user_age_embedding = tf.feature_column.numeric_column('user_age', dtype=tf.int64, default_value=0)
    user_gender_embedding = tf.feature_column.numeric_column('user_gender', dtype=tf.int64, default_value=0)
    user_pay_embedding = tf.feature_column.numeric_column('user_pay', dtype=tf.float32, default_value=0)
    package_type_embedding = tf.feature_column.numeric_column('package_typer', dtype=tf.int64, default_value=0)
    package_price_embedding = tf.feature_column.numeric_column('package_price', dtype=tf.int64, default_value=0)

    context_feature_columns['user_age'] = user_age_embedding
    context_feature_columns['user_gender'] = user_gender_embedding
    context_feature_columns['user_pay'] = user_pay_embedding
    context_feature_columns['package_type'] = package_type_embedding
    context_feature_columns['package_price'] = package_price_embedding

    return context_feature_columns

In [29]:
def create_example_feature_columns():
    example_feature_columns = {}
    item_type_embedding = tf.feature_column.numeric_column('item_type', dtype=tf.int64, default_value=0)
    item_cnt_embedding = tf.feature_column.numeric_column('item_cnt', dtype=tf.int64, default_value=0)

    example_feature_columns['item_type'] = item_type_embedding
    example_feature_columns['item_cnt'] = item_cnt_embedding

    return example_feature_columns

In [44]:
def make_dataset(file, batch_size, randomize_input=True, num_epochs=None):
    context_feature_columns = create_context_feature_columns()
    example_feature_columns = create_example_feature_columns()
    label_embedding = tf.feature_column.numeric_column(_LABEL_FEATURE, dtype=tf.int64, default_value=_PADDING_LABEL)

    context_feature_spec = tf.feature_column.make_parse_example_spec(context_feature_columns.values())
    print('context_feature_spec',context_feature_spec)
    example_feature_spec = tf.feature_column.make_parse_example_spec(list(example_feature_columns.values()) + [
        label_embedding])
    print('example_feature_spec',example_feature_spec)
    dataset = tfr.data.build_ranking_dataset(file_pattern=file,
                                            data_format=tfr.data.ELWC,
                                            batch_size=batch_size,
                                            context_feature_spec=context_feature_spec,
                                            example_feature_spec=example_feature_spec,
                                            reader=tf.data.TFRecordDataset,
                                            shuffle=randomize_input,
                                            num_epochs=num_epochs,
                                            size_feature_name=_SIZE)
    
    def _separate_features_and_label(features):
        #print(features)
        #tf.print('feature',features,output_stream=sys.stdout)
        label = tf.compat.v1.squeeze(features.pop(_LABEL_FEATURE), axis=2)
        label = tf.cast(label, tf.float32)
        #tf.print('label',label,output_stream=sys.stdout)
        return features, label

    dataset = dataset.map(_separate_features_and_label)
    return dataset

In [45]:
context_feature_columns = create_context_feature_columns()

In [46]:
example_feature_columns = create_example_feature_columns()

In [47]:
#Build a network it is a pointwise model
network = tfr.keras.canned.DNNRankingNetwork(context_feature_columns=context_feature_columns,
                                             example_feature_columns=example_feature_columns,
                                             hidden_layer_dims=[32, 16],
                                             activation=tf.nn.relu,
                                             dropout=0.5)

In [48]:
#loss
softmax_loss_obj = tfr.keras.losses.get(tfr.losses.RankingLossKey.SOFTMAX_LOSS)

In [49]:
#metric
default_metrics = tfr.keras.metrics.default_keras_metrics()

In [50]:
#optimizer
optimizer = tf.keras.optimizers.Adagrad(learning_rate=0.001)

In [51]:
#build ranker by Keras
ranker = tfr.keras.model.create_keras_model(network=network,
                                            loss=softmax_loss_obj,
                                            metrics=default_metrics,
                                            optimizer=optimizer,
                                            size_feature_name=_SIZE)

In [52]:
train_dataset = make_dataset("train_example.tfrecords", 1, num_epochs=-1)
val_dataset = make_dataset("train_example.tfrecords", 1, num_epochs=-1)

context_feature_spec {'user_age': FixedLenFeature(shape=(1,), dtype=tf.int64, default_value=(0,)), 'user_gender': FixedLenFeature(shape=(1,), dtype=tf.int64, default_value=(0,)), 'user_pay': FixedLenFeature(shape=(1,), dtype=tf.float32, default_value=(0,)), 'package_typer': FixedLenFeature(shape=(1,), dtype=tf.int64, default_value=(0,)), 'package_price': FixedLenFeature(shape=(1,), dtype=tf.int64, default_value=(0,))}
example_feature_spec {'item_type': FixedLenFeature(shape=(1,), dtype=tf.int64, default_value=(0,)), 'item_cnt': FixedLenFeature(shape=(1,), dtype=tf.int64, default_value=(0,)), 'relevance': FixedLenFeature(shape=(1,), dtype=tf.int64, default_value=(-1,))}
context_feature_spec {'user_age': FixedLenFeature(shape=(1,), dtype=tf.int64, default_value=(0,)), 'user_gender': FixedLenFeature(shape=(1,), dtype=tf.int64, default_value=(0,)), 'user_pay': FixedLenFeature(shape=(1,), dtype=tf.float32, default_value=(0,)), 'package_typer': FixedLenFeature(shape=(1,), dtype=tf.int64, def

In [53]:
for parsed_record in train_dataset.take(2):
    print(repr(parsed_record))

({'item_cnt': <tf.Tensor: shape=(1, 1, 1), dtype=int64, numpy=array([[[31]]])>, 'item_type': <tf.Tensor: shape=(1, 1, 1), dtype=int64, numpy=array([[[2]]])>, 'package_price': <tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[99]])>, 'package_typer': <tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[0]])>, 'user_age': <tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[5]])>, 'user_gender': <tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[0]])>, 'user_pay': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.94656116]], dtype=float32)>, 'example_list_size': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>}, <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.]], dtype=float32)>)
({'item_cnt': <tf.Tensor: shape=(1, 1, 1), dtype=int64, numpy=array([[[60]]])>, 'item_type': <tf.Tensor: shape=(1, 1, 1), dtype=int64, numpy=array([[[2]]])>, 'package_price': <tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[99]])>, 'package_typer': <tf.Tensor: shape=(1

In [54]:
ranker.fit(train_dataset,
           validation_data=val_dataset,
           steps_per_epoch=2,
           epochs=5,
           validation_steps=5)

Epoch 1/5
2/2 [==============================] - 5s 2s/step - loss: 0.0000e+00 - metric/ndcg_1: 0.5000 - metric/ndcg_3: 0.5000 - metric/ndcg_5: 0.5000 - metric/ndcg_10: 0.5000 - metric/arp: 1.0000 - metric/ordered_pair_accuracy: 0.0000e+00 - metric/mrr: 0.5000 - metric/precision: 0.5000 - metric/map: 0.5000 - metric/dcg: 0.5000 - metric/ndcg: 0.5000 - val_loss: 0.0000e+00 - val_metric/ndcg_1: 0.8000 - val_metric/ndcg_3: 0.8000 - val_metric/ndcg_5: 0.8000 - val_metric/ndcg_10: 0.8000 - val_metric/arp: 1.0000 - val_metric/ordered_pair_accuracy: 0.0000e+00 - val_metric/mrr: 0.8000 - val_metric/precision: 0.8000 - val_metric/map: 0.8000 - val_metric/dcg: 0.8000 - val_metric/ndcg: 0.8000
Epoch 2/5
2/2 [==============================] - 0s 100ms/step - loss: 0.0000e+00 - metric/ndcg_1: 0.5000 - metric/ndcg_3: 0.5000 - metric/ndcg_5: 0.5000 - metric/ndcg_10: 0.5000 - metric/arp: 1.0000 - metric/ordered_pair_accuracy: 0.0000e+00 - metric/mrr: 0.5000 - metric/precision: 0.5000 - metric/map: 0.5